[book]
title = "程序员入门指南"
#authors = ["本书编写组"]
language = "zh-CN"
multilingual = false
src = "src"

[output.html]
git-repository-url = "https://github.com/tsagaanbar/Newly-Programmer-ABC"
edit-url-template = "https://github.com/tsagaanbar/Newly-Programmer-ABC/edit/main/{path}"
mathjax-support = true
