name: Build Test
on:
  push:
  pull_request:
    branches:
      - main

jobs:
  build:
    name: mdBook build test

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup mdBook
        uses: peaceiris/actions-mdbook@v1
        with:
          mdbook-version: 'latest'

      - run: mdbook build

      - name: Upload artifact
        uses: actions/upload-artifact@v0
        with:
          path: ./book
          retention-days: 3
